mongodb:
  auth_source: null
  collections:
    inspection_units: xfaqpc_jzdwxx
    match_results: unit_match_results
    supervision_units: xxj_shdwjbxx
  connection_pool:
    # 基础超时配置 - 增加超时时间防止连接被拒绝
    connect_timeout_ms: 30000        # 连接超时：30秒
    server_selection_timeout_ms: 60000  # 服务器选择超时：60秒
    socket_timeout_ms: 120000        # Socket超时：2分钟
    wait_queue_timeout_ms: 60000     # 等待队列超时：60秒
    
    # 连接池配置 - 基于性能测试优化
    max_pool_size: 100               # 最大连接数：100（基于测试最优值）
    min_pool_size: 10                # 最小连接数：10
    max_connecting: 30               # 最大并发连接：30
    max_idle_time_ms: 60000          # 最大空闲时间：60秒
    
    # 新增配置项
    heartbeat_frequency_ms: 10000    # 心跳间隔：10秒
    retry_writes: true               # 启用写入重试
    retry_reads: true                # 启用读取重试
  database: Unit_Info
  host: localhost
  password: null
  port: 27017
  uri: mongodb://localhost:27017/Unit_Info
  username: null
redis:
  cache_ttl:
    match_progress: 60
    processed_units: 3600
    similarity_results: 1800
    user_session: 7200
  db: 0
  decode_responses: true
  host: localhost
  password: difyai123456
  port: 26379
  username: null
