address_similarity:
  city_weight: 0.3
  detail_weight: 0.2
  district_weight: 0.3
  enable_segmentation: true
  province_weight: 0.2
batch_processing:
  batch_size: 50
  enable_circuit_breaker: true
  max_workers: 4
  retry_times: 3
  timeout: 300
exact_match:
  fields:
    credit_code:
      priority: 1
      source_field: CREDIT_CODE
      target_field: tyshxydm
    unit_name:
      priority: 2
      source_field: UNIT_NAME
      target_field: dwmc
fuzzy_match:
  enable_entity_type_conflict_detection: true
  enable_industry_conflict_detection: true
  # 关键字段评分优化配置
  critical_field_validation:
    enabled: true  # 是否启用关键字段验证
    minimum_threshold: 0.4  # 关键字段最低评分阈值
    minimum_field_count: 2  # 触发验证的最少关键字段数量
  fields:
    address:
      match_type: address
      source_field: ADDRESS
      target_field: dwdz
      weight: 0.3
    legal_person:
      match_type: string
      source_field: LEGAL_PEOPLE
      target_field: fddbr
      weight: 0.15
    security_person:
      match_type: string
      source_field: SECURITY_PEOPLE
      target_field: xfaqglr
      weight: 0.15
    unit_name:
      match_type: string
      source_field: UNIT_NAME
      target_field: dwmc
      weight: 0.4
  reject_threshold: 0.25
  similarity_threshold: 0.6
  suspicious_threshold: 0.4
graph_matching:
  attribute_weights:
    address: 0.6
    legal_person: 1.0
  enabled: true
  initial_build_limit: 5000
logging:
  level: INFO
  log_match_decisions: true
  log_similarity_details: true
mongodb_optimization:
  connect_timeout_ms: 10000
  max_pool_size: 50
  min_pool_size: 5
  server_selection_timeout_ms: 5000
  socket_timeout_ms: 30000
numeric_similarity:
  building_area:
    max_diff: 0.2
    method: percentage_diff
phone_similarity:
  ignore_area_code: false
  match_mobile_landline: true
  normalize: true
result_saving:
  backup_interval: 1000
  save_interval: 10
string_similarity:
  algorithms:
  - name: levenshtein
    weight: 0.3
  - name: jaro_winkler
    weight: 0.3
  - name: cosine
    weight: 0.4
  chinese_processing:
    enable_jieba: true
    enable_pinyin: true
    normalize_spaces: true
    remove_punctuation: true
